# Generated by Django 5.0.4 on 2024-04-28 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=255)),
                ('company_logo', models.CharField(max_length=255)),
                ('company_url', models.CharField(max_length=255)),
                ('is_generated', models.BooleanField(default=False)),
                ('llm_model', models.CharField(max_length=255)),
                ('is_rag', models.BooleanField(default=False)),
                ('has_functions', models.BooleanField(default=False)),
                ('rag_dir', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('origin_info', models.TextField(blank=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot')),
            ],
        ),
    ]
